### ISSUE TITLE
Thanks for the nice work, but I fail to reproduce the results you published in the paper. I wonder is it possible for you to publish the parameter setting or providing more guidance for super-resolution?

### ISSUE THREAD

**Issue by YuboW0** [LituRout/PSLD#2]

**Comment by LituRout** [comment]
Thanks for the comment. We have given the hyper-parameter details for Stable diffusion in our paper; most of our experiments are done in this setting. For latent diffusion model as prior, maybe you can try omega=0.9 instead of 0.1. Another group of researchers found this configuration helpful while using latent diffusion models. 
 
Usually, you should see if the reconstructed image matches with the known parts of the image. If not, try to increase omega which controls the measurement consistency. Intuitively, you can try different combinations of omega and gamma where omega is slightly larger than gamma. 

I hope this addresses your concern. Please let me know if you have any other concerns.
