### ISSUE TITLE
the meaning of "x*_0" in Algorithm 2 

### ISSUE THREAD

**Issue by adaxigua** [LituRout/PSLD#6]
![image](https://github.com/LituRout/PSLD/assets/68674487/28325b64-47cb-46ea-8efd-e2ef6bd8d8fa)

What is the  meaning of  `x*_0` or `Ax*_0` ?  I can't find any definition. 

Thanks!

**Comment by LituRout** [comment]
Hi [wangherr](https://github.com/wangherr),

$x_0*$ denotes the unknown groundtruth image and $Ax_0*$ denotes the known measurements $y$. In case of noisy inverse problems, $y=Ax_0^* + noise$.

**Comment by adaxigua** [comment]
for line 8, 

I can understand it in inpainting.

if in others task, such as Gaussian deblur, 

1, will the `A A^T x*_0` to be `x_0` (groundtruth image)?
2, will the `I - A A^T` to be `0`?

thanks!

**Comment by LituRout** [comment]
As you have rightly pointed out, line 8 is self-explanatory for inpainting tasks. For Gaussian deblur, it is not clear what $A^T$ would be in this case. However, note that all linear inverse problems can be expressed as inpainting tasks at the cost of a big tedious measurement matrix $A$. Therefore, our algorithm generalizes to other linear inverse tasks.

In practice, we borrow the measurement operators from [DPS](https://github.com/DPS2022/diffusion-posterior-sampling/blob/effbde7325b22ce8dc3e2c06c160c021e743a12d/guided_diffusion/measurements.py#L130), which seems to work reasonably well.  

Note:- Q1 and Q2 above are incorrect because there is dimension mismatch between $A^T$ and $x_0*$. Above answer is for $A^TAx_0*$.

**Comment by adaxigua** [comment]
Is 'line 8' only used in inpainting tasks in practice?

**Comment by LituRout** [comment]
No, it is used for all the inverse tasks where A^T and A are chosen as per the DPS codebase. For inpainting, line 8 is exact and for other inverse tasks, it is an approximation.
